version: 2
registries:
  docker-private:
    type: docker-registry
    url: https://beyondtrust-docker.jfrog.io
    username: ${{ secrets.JFROG_READONLY_PLAIN_ACCESS_TOKEN_USER }}
    password: ${{ secrets.JFROG_READONLY_PLAIN_ACCESS_TOKEN }}
updates:
  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      exclude:
        - "beyondtrust/*"
        - "BeyondTrust/*"
    groups:
      minor-gomod:
        update-types:
          - minor
          - patch
      major-gomod:
        update-types:
          - major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      exclude:
        - "beyondtrust/*"
        - "BeyondTrust/*"
    groups:
      minor-gh-actions:
        update-types:
          - minor
          - patch
      major-gh-actions:
        update-types:
          - major
  - package-ecosystem: docker
    directories:
      - "**/*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      exclude:
        - "beyondtrust/*"
        - "BeyondTrust/*"
    registries:
      - docker-private
    commit-message:
      prefix: build(deps)
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
