_extends: .github
repository:
  private: false
  name: go-client-library-passwordsafe
  description: The Go client library for Password Safe enables Go developers to easily manage passwords from Password Safe. It provides simplifications that significantly reduce the amount of code you need to write.
  homepage: https://www.beyondtrust.com/
  topics: secrets, security, golang, library, beyondtrust, passwordsafe, secretssafe

