issues:
  exclude:
    - "Error return value of `*` is not checked"
    - "copylocks: Logging passes lock by value: log.Logger contains sync.Mutex"
  exclude-rules:
    - linters:
        errcheck
        govet
      text: "Error return value of `*` is not checked"

