-  params:
    git:
      repoName: go-client-library-passwordsafe
      branches:
        - main
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      projects:
        - workingDirs:
            - "."