name: SonarQube Analysis

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    environment: unit_test
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Generate App token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_BT_ACTIONS_READER_APP_ID }}
          private-key: ${{ secrets.GH_APP_BT_ACTIONS_READER_PEM }}
          owner: BeyondTrust

      - name: Checkout setup-jfrog-cli action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "BeyondTrust/setup-jfrog-cli"
          ref: "26d84636538c322aed2f822374a0b976b23caa81" # v2.4.3
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/setup-jfrog-cli

      - name: Setup JFrog
        uses: ./.github/actions/setup-jfrog-cli
        id: configure
        with:
          oidc-provider-name: "go-client-library-passwordsafe"

      - name: Build library
        run: |
          jf go-config --global --repo-resolve go --repo-deploy eng-go-qa-local
          jf go mod download
          jf go mod tidy
          go build

      - name: Run unit tests
        run: |
          cd api
          go test -race -coverprofile=coverage.out -v ./...
          go tool cover -func="coverage.out"
        env:
          PASSWORD_SAFE_FAKE_CERTIFICATE_KEY: ${{ vars.PASSWORD_SAFE_FAKE_CERTIFICATE_KEY }}
          PASSWORD_SAFE_FAKE_CERTIFICATE: ${{ vars.PASSWORD_SAFE_FAKE_CERTIFICATE }}
          PASSWORD_SAFE_FAKE_CLIENT_ID: ${{ vars.PASSWORD_SAFE_FAKE_CLIENT_ID }}
          PASSWORD_SAFE_FAKE_CLIENT_SECRET: ${{ vars.PASSWORD_SAFE_FAKE_CLIENT_SECRET }}
          PASSWORD_SAFE_FAKE_API_KEY: ${{ vars.PASSWORD_SAFE_FAKE_API_KEY }}
          PASSWORD_SAFE_API_PATH: ${{ vars.PASSWORD_SAFE_API_PATH }}
          PASSWORD_SAFE_FAKE_API_URL: ${{ vars.PASSWORD_SAFE_FAKE_API_URL }}
          PASSWORD_SAFE_FAKE_PASSWORD : ${{ vars.PASSWORD_SAFE_FAKE_PASSWORD }}

      - name: Save unit tests coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: api/coverage.out

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [unit-testing]
    permissions:
      actions: read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@8c1d1a09864211d258937b1b1a5b849f7e4f2682 # v1.2.0
        with:
          coverage-artifact-name: "coverage-report"
          coverage-file-name: "coverage.out"

  sonarqube:
    needs: [unit-testing]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Download coverage
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-report

      - name: SonarQube Scan on PR
        if: github.event_name == 'pull_request'
        uses: sonarsource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # v8.0.0
        with:
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.exclusions=api/**/**_test.go,api/entities/**,api/logging/**,api/utils/**,TestClient.go,performancetest/PerformanceTest.go,fuzzing/**
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonar.dev.beyondtrust.com

      - name: SonarQube Scan on Branch
        if: github.event_name == 'push'
        uses: sonarsource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # v8.0.0
        with:
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.exclusions=api/**/**_test.go,api/entities/**,api/logging/**,api/utils/**,TestClient.go,performancetest/PerformanceTest.go,fuzzing/**
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonar.dev.beyondtrust.com
