name: SonarQube Analysis

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

permissions: {}

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    environment: unit_test
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Generate App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_BT_ACTIONS_READER_APP_ID }}
          private-key: ${{ secrets.GH_APP_BT_ACTIONS_READER_PEM }}
          owner: BeyondTrust

      - name: Checkout setup-jfrog-cli action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "BeyondTrust/setup-jfrog-cli"
          ref: "26d84636538c322aed2f822374a0b976b23caa81" # v2.4.3
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/setup-jfrog-cli

      - name: Setup JFrog
        uses: ./.github/actions/setup-jfrog-cli
        id: configure
        with:
          oidc-provider-name: "go-client-library-passwordsafe"

      - name: Build library
        run: |
          jf go-config --global --repo-resolve go --repo-deploy eng-go-qa-local
          jf go mod download
          jf go mod tidy
          go build

      - name: Run unit tests
        run: |
          cd api
          go test -race -coverprofile=coverage.out -v ./...
          go tool cover -func="coverage.out"
        env:
          PASSWORD_SAFE_FAKE_CERTIFICATE_KEY: ${{ vars.PASSWORD_SAFE_FAKE_CERTIFICATE_KEY }}
          PASSWORD_SAFE_FAKE_CERTIFICATE: ${{ vars.PASSWORD_SAFE_FAKE_CERTIFICATE }}
          PASSWORD_SAFE_FAKE_CLIENT_ID: ${{ vars.PASSWORD_SAFE_FAKE_CLIENT_ID }}
          PASSWORD_SAFE_FAKE_CLIENT_SECRET: ${{ vars.PASSWORD_SAFE_FAKE_CLIENT_SECRET }}
          PASSWORD_SAFE_FAKE_API_KEY: ${{ vars.PASSWORD_SAFE_FAKE_API_KEY }}
          PASSWORD_SAFE_API_PATH: ${{ vars.PASSWORD_SAFE_API_PATH }}
          PASSWORD_SAFE_FAKE_API_URL: ${{ vars.PASSWORD_SAFE_FAKE_API_URL }}
          PASSWORD_SAFE_FAKE_PASSWORD : ${{ vars.PASSWORD_SAFE_FAKE_PASSWORD }}

      - name: Save unit tests coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report
          path: api/coverage.out

  sonarqube:
    needs: [unit-testing]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Generate App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_BT_ACTIONS_READER_APP_ID }}
          private-key: ${{ secrets.GH_APP_BT_ACTIONS_READER_PEM }}
          owner: BeyondTrust

      - name: Checkout sonarqube action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: BeyondTrust/workflows
          ref: 51e9f52f8446a28edae9c7277ce1a612b86570ea # v4.13.1
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/sonarqube

      - name: Download coverage
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: coverage-report

      - name: SonarQube Scan
        uses: ./.github/actions/sonarqube
        with:
          coverage_artifact: coverage-report
          coverage_artifact_path: .
          required_coverage_files: coverage.out
          extra_flags: >-
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.exclusions=api/**/**_test.go,api/entities/**,api/logging/**,api/utils/**,TestClient.go,performancetest/PerformanceTest.go,fuzzing/**
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonar.dev.beyondtrust.com
